# Generated by Django 4.2 on 2023-05-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_reviews_score'),
        ('users', '0002_alter_userfollowing_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_title',
        ),
        migrations.AddField(
            model_name='user',
            name='liked_film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_liked_film', to='titles.title'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_liked_series', to='titles.title'),
        ),
    ]
