# Generated by Django 4.2 on 2023-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_initial'),
        ('users', '0002_alter_user_avatar_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watched_titles',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_watched', to='titles.title'),
        ),
    ]
