# Generated by Django 4.2 on 2023-05-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='genres/'),
        ),
    ]
