# Generated by Django 4.2 on 2023-04-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='person_image'),
        ),
    ]
