# Generated by Django 4.2 on 2023-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_alter_genres_description_alter_genres_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='score',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
